services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: grtech-admin:latest
    container_name: grtech-admin-app
    restart: always
    ports:
      - "8001:80"
    volumes:
      # Ganti ./ dengan nama volume permanen untuk menyimpan data SQLite
      - grtech_sqlite_data:/var/www/html/storage/app
    environment:
      - APP_ENV=${APP_ENV}
      - APP_DEBUG=${APP_DEBUG}
      - DB_CONNECTION=${DB_CONNECTION}
      - DB_DATABASE=${DB_DATABASE}
      - APP_URL=${APP_URL}

volumes:
  grtech_sqlite_data:
    driver: local